cc_binary(
  name = "memcheck",
  srcs = ["memcheck_main.cpp"],
)

cc_binary(
  name = "callgrind",
  srcs = ["callgrind_main.cpp"],
)

cc_binary(
  name = "cachegrind_array",
  srcs = ["cachegrind_array.cpp"],
)

cc_binary(
  name = "cachegrind_list",
  srcs = ["cachegrind_list.cpp"],
)
