cc_library(
    name = "application",
    hdrs = ["application.h"],
)

cc_test(
  name = "application_test",
  srcs = ["test.cpp"],
  deps = ["@gtest//:gtest",
        "@gtest//:gtest_main",
        ":application",
        ],
  
)